apiVersion: v1
kind: Service
metadata:
  name: express-test-service
spec:
  selector:
    app: express-test-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 3010
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-test-app
spec:
  selector:
    matchLabels:
      app: express-test-app
  replicas: 2
  template:
    metadata:
      labels:
        app: express-test-app
    spec:
      containers:
      - name: express-test-app
        image: app-1-k8s:1
        imagePullPolicy: Never
        ports:
        - containerPort: 3010